name: Hello World!

on:
  push:
    paths:
      - 'part11/full-stack-open-pokedex/**'
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"